import { CampaignData, EventData, LocationData, ScheduleData } from '@/types';

export const INITIAL_CAMPAIGN: CampaignData = {
  id: 'cmp-guntur-2026',
  name: 'Guntur MP Constituency Campaign 2026',
  candidateName: 'Hon. Nara Lokesh',
  constituency: 'Guntur Parliamentary Constituency',
  startDate: '2026-08-01',
  endDate: '2026-09-30',
  timezone: 'Asia/Kolkata',
};

export const INITIAL_LOCATIONS: LocationData[] = [
  {
    id: 'loc-1',
    campaignId: 'cmp-guntur-2026',
    name: 'Brodipet Main Party Office',
    address: '4th Line, Brodipet, Guntur, AP 522002',
    latitude: 16.3067,
    longitude: 80.4365,
    placeId: 'ChIJz3K4y_l3TjoR5H1tF8WqA-A',
    category: 'PARTY_OFFICE',
  },
  {
    id: 'loc-2',
    campaignId: 'cmp-guntur-2026',
    name: 'District Collectorate Assembly Hall',
    address: 'Collectorate Compound, Guntur, AP 522004',
    latitude: 16.2991,
    longitude: 80.4485,
    placeId: 'ChIJp2sL76J3TjoR00x2s-917sK',
    category: 'GOVERNMENT_OFFICE',
  },
  {
    id: 'loc-3',
    campaignId: 'cmp-guntur-2026',
    name: 'Mangalagiri Municipal Convention Center',
    address: 'GT Road, Mangalagiri, Guntur District, AP 522503',
    latitude: 16.4348,
    longitude: 80.5501,
    placeId: 'ChIJX99l8Zp3TjoRF8Qv5-tS988',
    category: 'MEETING_HALL',
  },
  {
    id: 'loc-4',
    campaignId: 'cmp-guntur-2026',
    name: 'Tadikonda Farmers & Youth Ground',
    address: 'Tadikonda Main Village, Guntur District, AP 522236',
    latitude: 16.4172,
    longitude: 80.4502,
    placeId: 'ChIJj70dF812TjoR72s3_89skL1',
    category: 'VILLAGE',
  },
  {
    id: 'loc-5',
    campaignId: 'cmp-guntur-2026',
    name: 'Tenali Municipal Stadium Grounds',
    address: 'Station Road, Tenali, AP 522201',
    latitude: 16.2430,
    longitude: 80.6400,
    placeId: 'ChIJL33s9212TjoR98wKk-182sL',
    category: 'PUBLIC_MEETING',
  },
  {
    id: 'loc-6',
    campaignId: 'cmp-guntur-2026',
    name: 'Pedakakani Temple Junction Grounds',
    address: 'Temple Road, Pedakakani, Guntur, AP 522509',
    latitude: 16.3385,
    longitude: 80.5050,
    placeId: 'ChIJq-192sL2TjoR-10928sksL3',
    category: 'TEMPLE',
  },
];

export const INITIAL_EVENTS: EventData[] = [
  {
    id: 'evt-1',
    campaignId: 'cmp-guntur-2026',
    locationId: 'loc-1',
    title: 'Morning Strategy & Media Briefing',
    description: 'Daily morning review with campaign chiefs and press core.',
    eventType: 'PRESS_CONF',
    date: '2026-08-28',
    preferredStart: '08:30',
    preferredEnd: '09:15',
    fixedStart: null,
    fixedEnd: null,
    durationMinutes: 45,
    priority: 80,
    isFixed: false,
    isFlexible: true,
    status: 'PLANNED',
  },
  {
    id: 'evt-2',
    campaignId: 'cmp-guntur-2026',
    locationId: 'loc-2',
    title: 'District Collector Security & Model Code Meeting',
    description: 'Mandatory official meeting with District Magistrate & Election Officer.',
    eventType: 'VIP_MEETING',
    date: '2026-08-28',
    preferredStart: '10:30',
    preferredEnd: '11:30',
    fixedStart: '10:30',
    fixedEnd: '11:30',
    durationMinutes: 60,
    priority: 100,
    isFixed: true,
    isFlexible: false,
    status: 'PLANNED',
  },
  {
    id: 'evt-3',
    campaignId: 'cmp-guntur-2026',
    locationId: 'loc-3',
    title: 'Mangalagiri Weavers & IT Park Delegation',
    description: 'Interact with local weavers association and tech community representatives.',
    eventType: 'MEETING',
    date: '2026-08-28',
    preferredStart: '12:00',
    preferredEnd: '13:00',
    fixedStart: null,
    fixedEnd: null,
    durationMinutes: 60,
    priority: 90,
    isFixed: false,
    isFlexible: true,
    status: 'PLANNED',
  },
  {
    id: 'evt-4',
    campaignId: 'cmp-guntur-2026',
    locationId: 'loc-4',
    title: 'Tadikonda Village Palle Nidra & Farmers Interaction',
    description: 'Village walkthrough and discussion on agricultural water schemes.',
    eventType: 'VILLAGE_VISIT',
    date: '2026-08-28',
    preferredStart: '14:30',
    preferredEnd: '15:30',
    fixedStart: null,
    fixedEnd: null,
    durationMinutes: 60,
    priority: 85,
    isFixed: false,
    isFlexible: true,
    status: 'PLANNED',
  },
  {
    id: 'evt-5',
    campaignId: 'cmp-guntur-2026',
    locationId: 'loc-5',
    title: 'Tenali Constituency Public Mega Rally',
    description: 'Addressing 25,000+ citizens at Tenali Stadium.',
    eventType: 'PUBLIC_MEETING',
    date: '2026-08-28',
    preferredStart: '17:30',
    preferredEnd: '19:00',
    fixedStart: '17:30',
    fixedEnd: '19:00',
    durationMinutes: 90,
    priority: 100,
    isFixed: true,
    isFlexible: false,
    status: 'PLANNED',
  },
  {
    id: 'evt-6',
    campaignId: 'cmp-guntur-2026',
    locationId: 'loc-6',
    title: 'Pedakakani Temple Darshan & Community Greeting',
    description: 'Evening visit and greeting local citizens.',
    eventType: 'TEMPLE',
    date: '2026-08-28',
    preferredStart: '16:00',
    preferredEnd: '16:45',
    fixedStart: null,
    fixedEnd: null,
    durationMinutes: 45,
    priority: 70,
    isFixed: false,
    isFlexible: true,
    status: 'PLANNED',
  },
];
