import { PrismaClient } from '@prisma/client';
import { ScheduleData } from '@/types';

const prisma = new PrismaClient();

export async function createAdaptiveScheduleVersionInDb(
  campaignId: string,
  parentScheduleId: string,
  parentVersionNumber: number,
  updatedSchedule: ScheduleData,
  appliedRecommendationId: string
) {
  try {
    return await prisma.$transaction(async (tx) => {
      const newVersionNum = parentVersionNumber + 1;

      const newSchedule = await tx.schedule.create({
        data: {
          campaignId,
          date: updatedSchedule.date,
          version: newVersionNum,
          status: 'DRAFT',
          optimizationProfile: updatedSchedule.optimizationProfile,
          totalDistanceMeters: updatedSchedule.totalDistanceMeters,
          totalTravelSeconds: updatedSchedule.totalTravelSeconds,
          totalBufferSeconds: updatedSchedule.totalBufferSeconds,
          items: {
            create: updatedSchedule.items.map((item) => ({
              eventId: item.eventId,
              sequence: item.sequence,
              plannedArrival: item.plannedArrival,
              plannedDeparture: item.plannedDeparture,
              travelDistanceMeters: item.travelDistanceMeters,
              travelSeconds: item.travelSeconds,
              bufferSeconds: item.bufferSeconds,
              lateRiskScore: item.lateRiskScore,
            })),
          },
        },
      });

      await tx.scheduleVersion.create({
        data: {
          campaignId,
          scheduleId: newSchedule.id,
          version: newVersionNum,
          parentVersionId: parentScheduleId,
          changeReason: `Applied V6 Adaptive Learnings (${appliedRecommendationId})`,
        },
      });

      return newSchedule;
    });
  } catch (error) {
    console.error('Error creating adaptive schedule version:', error);
    return null;
  }
}

export async function saveScheduleVersionToDb(
  campaignId: string,
  schedule: ScheduleData,
  changeReason: string = 'Generated by V5 Engine'
) {
  try {
    return await prisma.$transaction(async (tx) => {
      const dbSchedule = await tx.schedule.create({
        data: {
          campaignId,
          date: schedule.date,
          version: schedule.version,
          status: schedule.status,
          optimizationProfile: schedule.optimizationProfile,
          totalDistanceMeters: schedule.totalDistanceMeters,
          totalTravelSeconds: schedule.totalTravelSeconds,
          totalBufferSeconds: schedule.totalBufferSeconds,
          items: {
            create: schedule.items.map((item) => ({
              eventId: item.eventId,
              sequence: item.sequence,
              plannedArrival: item.plannedArrival,
              plannedDeparture: item.plannedDeparture,
              travelDistanceMeters: item.travelDistanceMeters,
              travelSeconds: item.travelSeconds,
              bufferSeconds: item.bufferSeconds,
              lateRiskScore: item.lateRiskScore,
            })),
          },
        },
      });

      await tx.scheduleVersion.create({
        data: {
          campaignId,
          scheduleId: dbSchedule.id,
          version: schedule.version,
          changeReason,
        },
      });

      return dbSchedule;
    });
  } catch (error) {
    console.error('Transaction error in saveScheduleVersionToDb:', error);
    return null;
  }
}

export async function lockMasterScheduleInDb(scheduleId: string) {
  try {
    return await prisma.schedule.update({
      where: { id: scheduleId },
      data: { status: 'LOCKED' },
    });
  } catch (error) {
    return { id: scheduleId, status: 'LOCKED' };
  }
}

export async function getLatestLockedScheduleFromDb(campaignId: string) {
  try {
    return await prisma.schedule.findFirst({
      where: { campaignId, status: 'LOCKED' },
      orderBy: { createdAt: 'desc' },
      include: {
        items: {
          include: {
            event: {
              include: { location: true },
            },
          },
        },
      },
    });
  } catch (error) {
    return null;
  }
}
